name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y devscripts libxcb-cursor-dev libxcb-keysyms1-dev libxcb-util-dev libxkbcommon-dev libxkbcommon-x11-dev ninja-build xcb libgtk-3-dev libwebkit2gtk-4.0 libwebkit2gtk-4.0-dev libcurl4-openssl-dev alsa alsa-tools libasound2-dev libjack-dev libfreetype6-dev libxinerama-dev libxcb-xinerama0 libxinerama1 x11proto-xinerama-dev libxrandr-dev libgl1-mesa-dev libxcursor-dev libxcursor1 libxcb-cursor-dev libxcb-cursor0 libusb-1.0.0-dev patchelf

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: cmake -Bignore/build -DCMAKE_BUILD_TYPE=Debug
      - run: cmake --build ignore/build --parallel $(nproc || echo 1)
